### ISSUE TITLE
Please add our paper to this list.

### ISSUE THREAD

**Issue by revanurambareesh** [ayushidalmia/awesome-fashion-ai#13]
Semi-Supervised Visual Representation Learning for Fashion Compatibility (ACM RecSys'21)

I have raised a pull request for the same. Please check #12 

Thanks!

**Comment by joppichristian** [comment]
Please add also our paper: MovingFashion: a Benchmark for the Video-to-Shop Challenge
(https://arxiv.org/abs/2110.02627) 

Thanks!
