### ISSUE TITLE
Please kindly add our ICCV2019 work

### ISSUE THREAD

**Issue by wenguanwang** [ayushidalmia/awesome-fashion-ai#4]
Could you please kindly add our ICCV2019 work, Learning Compositional Neural Information Fusion for Human Parsing (https://www.researchgate.net/publication/335467236_Learning_Compositional_Neural_Information_Fusion_for_Human_Parsing), which ranks third in CVPR19 LIP Challenge: Single-Person Human Parsing Track.

Thanks.

**Comment by ayushidalmia** [comment]
Thanks @wenguanwang. Congratulations!

The focus of this repository is to primarily show case applied work related to fashion and maybe retail. This paper is on  core area of human parsing and hence I am not including it right now. 

Hope this is ok. 
Thanks!

**Comment by codereba** [comment]
Thanks, It is very interesting.
What is the detail?

I will try to improve this project, and I have a job, You kown.

Nice to meet you, thanks.
________________________________

**Comment by wenguanwang** [comment]
@codereba 
You can find it here
http://openaccess.thecvf.com/content_ICCV_2019/papers/Wang_Learning_Compositional_Neural_Information_Fusion_for_Human_Parsing_ICCV_2019_paper.pdf

Thanks.
