### ISSUE TITLE
Codes available?

### ISSUE THREAD

**Issue by ghost** [ayushidalmia/awesome-fashion-ai#5]
Hi, 

Is there a similar compilation of the papers who have made their codes available online?

I'm particularly looking for the "Creating capsule wardrobes" paper code but can't find it anywhere. Can you please nudge me in the right direction?

TIA

**Comment by ayushidalmia** [comment]
Hi, 
I will try to add link to code from the original authors or someone else as I find it. Thanks for the suggestion. Please feel free to contribute by creating issue for related papers.
